### ISSUE TITLE
[Resolved] Problem with setting up your account of the incentive program in the MiniDapp System

### ISSUE THREAD

**Issue by an-trader** [minima-global/MiniDAPP#6]
Help solve the problem

I describe the problem step by step:
Ubuntu 20.04.5
Console MobaXterm
Google Chrome and Brave
I tried turning off antivirus and browser extensions
---
1. I go to https://MyServerIP:9003/ in Google Chrome web browser and see the login page
![image](https://user-images.githubusercontent.com/87753268/211395014-dcbc9455-9b19-4cf9-aa7e-46a549a80272.png)

2. I enter my password and get to the confirmation page and press the main menu button:
![image](https://user-images.githubusercontent.com/87753268/211396003-b2a3b7f0-ca9a-44c1-b85d-7d5fd59a8d8a.png)

Then I get to the applications page and choose: "Incentive Program
![image](https://user-images.githubusercontent.com/87753268/211396901-9c657623-726f-477c-8457-fadc6a52e79b.png)

3. I enter my Incentive ID, which is taken here:
https://incentivecash.minima.global/home/pages/incentiveid
![image](https://user-images.githubusercontent.com/87753268/211397394-9ac5e241-f4bf-4af8-99ba-9f5bf919f77f.png)

Pressing the Update button:
![image](https://user-images.githubusercontent.com/87753268/211397968-09357f7b-51de-4027-bfa7-dbdde2968f52.png)

4. Then no matter how long I wait, when I go to the "Rewards" section a message appears:
Then no matter how long I wait, when I go to the "Rewards" section a message appears:
Please connect your Incentive ID to view your Rewards.
![image](https://user-images.githubusercontent.com/87753268/211398702-e87d587a-fd4f-4db0-a1f3-e59b24588f15.png)

5. I go back to "Incentive ID" and there is an empty Incentive ID field:
![image](https://user-images.githubusercontent.com/87753268/211399114-a7c5c98f-5dfc-4e20-96b0-e441a9547643.png)

Information about my minima in the SSH console:
```
docker exec -it minima9001 minima
status
```
![image](https://user-images.githubusercontent.com/87753268/211399885-95f14afe-234b-4f93-871d-1e9c9d51dceb.png)

![image](https://user-images.githubusercontent.com/87753268/211400064-a6ff27b9-90e4-4da3-a3f6-f1ecd645bd31.png)

`curl -s 127.0.0.1:9005/status | jq '{"Version":.response.version,"Block height":.response.chain.block, "Block time":.response.chain.time}'`
![image](https://user-images.githubusercontent.com/87753268/211400357-b662bd9d-b2bc-4a1c-9e0b-8baed31a14db.png)

`curl 127.0.0.1:9005/incentivecash | jq`
![image](https://user-images.githubusercontent.com/87753268/211400685-2c25889a-9827-4496-8cf0-830b8655ee81.png)

**Comment by dynamitesushi** [comment]
@an-trader 

Hello, thank you for creating an issue. Out of curiosity what happens when you visit https://localhost:9004 in your browser? Do you get a cert error? If yes, can you ignore the cert error and try the MiniDApp again please?

**Comment by an-trader** [comment]
`https://localhost:9004/`
![image](https://user-images.githubusercontent.com/87753268/211554238-cb08439d-c0ae-457f-8125-50e71abceaa9.png)

English:
![image](https://user-images.githubusercontent.com/87753268/211555436-05feb8f9-68c7-4ede-918f-7f8e343a0b35.png)

As far as I understand, when accessing https://localhost:9004/ nothing can open because on my local PC there is no software that allows to open the web page

**Comment by dynamitesushi** [comment]
@an-trader   

Can you confirm the docker ports that are used by running using `docker container ls` in the CLI or a picture of docker desktop? Seems like your MDS port isn't open on 9004 which is used to communicate with Minima which is why it's failing via the MiniDApp.

**Comment by an-trader** [comment]
In the MobaXterm terminal I enter the command:
`docker container ls`
![image](https://user-images.githubusercontent.com/87753268/211596775-09d3c2be-fc98-407f-b693-2382cb040654.png)


![image](https://user-images.githubusercontent.com/87753268/211603740-3ebea238-4d03-4e45-b962-eb4b9262768d.png)

The text can be typed, but Enter is not pressed
![image](https://user-images.githubusercontent.com/87753268/211604245-13bd9a35-3363-4793-8f22-ad224fed7d36.png)

**Comment by an-trader** [comment]
Minima is installed on an Ubuntu 20.04 server (no desktop) - my hosting provider is Hetzner.
I have Windows 10 Pro installed on my local PC, and I use my browser to log in to https://MyServerIP:9003/ and log in to MDS.

Entering the address https://localhost:9004 into the address bar will give no result because port 9004 is not used on the local PC - Minima is installed on a remote server.
In fact, the local PC knows nothing about Minima.

Or maybe I don't understand it.

**Comment by an-trader** [comment]
In the MobaXterm terminal
`sudo iptables -L`
![image](https://user-images.githubusercontent.com/87753268/211616191-afd56aca-f135-4913-b2bf-7257a0ba504a.png)

`nc -zvw3 MyServerIP 9004` and `nc -zvw3 MyServerIP 9003`
![image](https://user-images.githubusercontent.com/87753268/211617922-df85ee06-fab6-42ef-b1ee-176e97d4e176.png)

**Comment by dynamitesushi** [comment]
@an-trader 

Ah you're running it on a server, can you try https://your-remote-ip:9004 then ignore the https error and try the MiniDApp again?

**Comment by an-trader** [comment]
![image](https://user-images.githubusercontent.com/87753268/211630243-747b3ad3-27eb-44b6-b9b4-bc42e4f705de.png)

Next:
![image](https://user-images.githubusercontent.com/87753268/211630735-745692fd-0e71-48ab-9194-4c75991631e5.png)


Next:
![image](https://user-images.githubusercontent.com/87753268/211631275-641e76c0-5b22-44d6-87f0-3f4ae3f4b4a1.png)

**Comment by an-trader** [comment]
![image](https://user-images.githubusercontent.com/87753268/211631799-cf9a80ab-2245-48c3-bb23-f6b3db96a6f3.png)

Problem solved
![image](https://user-images.githubusercontent.com/87753268/211631978-69005c11-6e77-4755-b32c-1ba372d32e6e.png)

**Comment by an-trader** [comment]
Thank you for your help

**Comment by dynamitesushi** [comment]
@an-trader 

Is everything working now? :)
